site_name: London Bikes
repo_url: https://github.com/nico-or/data_london_bikes
copyright: Copyright &copy; 2025 Nicolás Órdenes

theme:
    name: material
    features:
        - navigation.footer

markdown_extensions:
    - pymdownx.highlight:
          linenums: true
    - pymdownx.superfences

nav:
    - "index.md"
    - "Prepare":
          - "prepare/index.md"
          - "prepare/gather.md"
          - "prepare/describe.md"
          - "prepare/model.md"
          - "prepare/load.md"
    - "Explore":
          - "explore/index.md"
          - "explore/dates.md"
          - "explore/bikes.md"
          - "explore/stations.md"
          - "explore/trip_durations.md"
    - "Process":
          - "process/index.md"
          - "process/validate.md"
          - "process/normalize.md"
          - "process/extend.md"
    - "Analyze":
          - "analyze/index.md"
          - "analyze/trips.md"
          - "analyze/bikes.md"
