site_name: London Bikes
nav:
  - "index.md"
  - "Collection":
      - "collection/index.md"
      - "collection/gathering.md"
      - "collection/description.md"
  - "Process":
      - "process/index.md"
      - "process/load.md"
  - "Analysis":
      - "analysis/index.md"
      - "analysis/trips.md"
      - "analysis/bikes.md"
